/*v
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import static hotel.Sql.connectDB;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author CHON_STRIX
 */
public class Forgetpassword extends javax.swing.JFrame {

    /**
     * Creates new form UI_login
     */
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
        
    int mouseX;
    int mouseY;
    
    int staff_id;
    public Forgetpassword() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Group_confirm = new javax.swing.JPanel();
        phone_confirm1 = new javax.swing.JPanel();
        close_f3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        phone_forget = new javax.swing.JTextField();
        forgetPass_button = new javax.swing.JButton();
        email_forget = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        password_confirm = new javax.swing.JPanel();
        close_f1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Password2 = new javax.swing.JPasswordField();
        Password1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        Group_confirm.setBackground(new java.awt.Color(102, 0, 153));
        Group_confirm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Group_confirm.setLayout(new java.awt.CardLayout());

        phone_confirm1.setBackground(new java.awt.Color(102, 0, 153));
        phone_confirm1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        close_f3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close icon_1.png"))); // NOI18N
        close_f3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_f3MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email :");

        phone_forget.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        forgetPass_button.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        forgetPass_button.setText("Confirm");
        forgetPass_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgetPass_buttonActionPerformed(evt);
            }
        });

        email_forget.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone Number :");

        javax.swing.GroupLayout phone_confirm1Layout = new javax.swing.GroupLayout(phone_confirm1);
        phone_confirm1.setLayout(phone_confirm1Layout);
        phone_confirm1Layout.setHorizontalGroup(
            phone_confirm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, phone_confirm1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(close_f3))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, phone_confirm1Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(phone_confirm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(forgetPass_button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(phone_confirm1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(email_forget, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(phone_confirm1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(phone_forget, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(86, 86, 86))
        );
        phone_confirm1Layout.setVerticalGroup(
            phone_confirm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phone_confirm1Layout.createSequentialGroup()
                .addComponent(close_f3)
                .addGap(18, 18, 18)
                .addGroup(phone_confirm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone_forget, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(33, 33, 33)
                .addGroup(phone_confirm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_forget, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(36, 36, 36)
                .addComponent(forgetPass_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        Group_confirm.add(phone_confirm1, "card2");

        password_confirm.setBackground(new java.awt.Color(102, 0, 153));
        password_confirm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        close_f1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close icon_1.png"))); // NOI18N
        close_f1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_f1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Confirm Password :");

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jButton2.setText("Confirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("New Password :");

        Password2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Password2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password2ActionPerformed(evt);
            }
        });

        Password1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout password_confirmLayout = new javax.swing.GroupLayout(password_confirm);
        password_confirm.setLayout(password_confirmLayout);
        password_confirmLayout.setHorizontalGroup(
            password_confirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(password_confirmLayout.createSequentialGroup()
                .addGap(492, 492, 492)
                .addComponent(close_f1))
            .addGroup(password_confirmLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Password1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(password_confirmLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Password2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(password_confirmLayout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        password_confirmLayout.setVerticalGroup(
            password_confirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(password_confirmLayout.createSequentialGroup()
                .addComponent(close_f1)
                .addGap(20, 20, 20)
                .addGroup(password_confirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Password1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(password_confirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Password2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        Group_confirm.add(password_confirm, "card3");

        getContentPane().add(Group_confirm, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void close_f1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_f1MouseClicked
        new Login_Form().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_close_f1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Connection con = connectDB();
        String sql_p = "update staff set password = ? where staff_id = ?";
        String pass1 = new String(Password1.getPassword());
        String pass2 = new String(Password2.getPassword());
        String Textstaff_id = Integer.toString(staff_id);

        if(pass1.isEmpty() && pass2.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Input Before !\n");
        }
        else
        {
            if(pass1.equals(pass2))
            {
                try
                {
                    pst = con.prepareStatement(sql_p);
                    pst.setString(1, pass2);
                    pst.setString(2, Textstaff_id);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Password Changed");
                    new Login_Form().setVisible(true);
                    this.setVisible(false);
                }   
                catch (SQLException e) 
                {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Please Check Password Again");
            }
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void close_f3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_f3MouseClicked
        new Login_Form().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_close_f3MouseClicked

    private void forgetPass_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgetPass_buttonActionPerformed
        Connection con = connectDB();
        String sql = "select staff_id,email,phone from staff where phone = ? and email = ?";
        
        if(phone_forget.getText().isEmpty() && email_forget.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Input Before !\n");
        }
        else
        {
            try
            {
                pst = con.prepareStatement(sql);
                pst.setString(1, phone_forget.getText());
                pst.setString(2, email_forget.getText());
                rs = pst.executeQuery();

                if(rs.next())
                {
                    staff_id = rs.getInt(1);
                    System.out.println(staff_id);
                        Group_confirm.removeAll();
                        Group_confirm.repaint();
                        Group_confirm.revalidate();

                        Group_confirm.add(password_confirm);
                        Group_confirm.repaint();
                        Group_confirm.revalidate();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Invalid !...\nUsername and Password");
                }
            }   
            catch (SQLException e) 
            {
            JOptionPane.showMessageDialog(null, e);
            }
        }


    }//GEN-LAST:event_forgetPass_buttonActionPerformed

    private void Password2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgetpassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Group_confirm;
    private javax.swing.JPasswordField Password1;
    private javax.swing.JPasswordField Password2;
    private javax.swing.JLabel close_f1;
    private javax.swing.JLabel close_f3;
    private javax.swing.JTextField email_forget;
    private javax.swing.JButton forgetPass_button;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel password_confirm;
    private javax.swing.JPanel phone_confirm1;
    private javax.swing.JTextField phone_forget;
    // End of variables declaration//GEN-END:variables

    private static class e {

        public e() {
        }
    }
}
